import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Check, Download, FileText } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface PRDSection {
  id: string;
  name: string;
  phase: string;
  content: string;
}

interface ExportPanelProps {
  sections: PRDSection[];
  projectName: string;
}

type Platform = "lovable" | "cursor" | "bolt";

const PLATFORM_INFO: Record<Platform, { name: string; description: string; format: (sections: PRDSection[], projectName: string) => string }> = {
  lovable: {
    name: "Lovable",
    description: "Optimized prompt sequence for Lovable's AI builder",
    format: (sections, projectName) => {
      const plan = sections.filter((s) => s.phase === "Plan");
      const build = sections.filter((s) => s.phase === "Build");
      const improve = sections.filter((s) => s.phase === "Improve");

      return `# ${projectName} — Complete PRD for Lovable
# Generated by Prompt Pilot (VibeCoder Studio)
#
# ⚡ HOW TO USE IN LOVABLE (3-Step Paste Workflow)
# ─────────────────────────────────────────────────
# 1. Copy PROMPT 1 below → Paste into Lovable → Wait for it to finish building
# 2. Copy PROMPT 2 below → Paste into Lovable → Wait for it to finish building
# 3. Copy PROMPT 3 below → Paste into Lovable → Done!
#
# 🚨 IMPORTANT: Do NOT paste everything at once.
# Lovable works best when you feed it one phase at a time.
# Each prompt builds on what the previous one created.

${"━".repeat(60)}
PROMPT 1 OF 3 — FOUNDATION (Vision + UX + Database)
${"━".repeat(60)}
Paste this into Lovable first. This sets up your project
structure, user experience, and data model.

${plan.map((s) => `### ${s.id}: ${s.name}\n${s.content}`).join("\n\n")}

${"━".repeat(60)}
PROMPT 2 OF 3 — BUILD (Full App + SaaS Logic + Design)
${"━".repeat(60)}
Paste this after Prompt 1 is done. This builds the full
application on top of the foundation.

${build.map((s) => `### ${s.id}: ${s.name}\n${s.content}`).join("\n\n")}

${"━".repeat(60)}
PROMPT 3 OF 3 — POLISH (Features + QA + Optimization)
${"━".repeat(60)}
Paste this last. This adds advanced features, fixes edge
cases, and optimizes performance.

${improve.map((s) => `### ${s.id}: ${s.name}\n${s.content}`).join("\n\n")}
`;
    },
  },
  cursor: {
    name: "Cursor",
    description: "Structured for Cursor's AI code editor workflow",
    format: (sections, projectName) => {
      return `# ${projectName} — PRD for Cursor
# Generated by Prompt Pilot (VibeCoder Studio)
# 
# HOW TO USE IN CURSOR:
# 1. Open Cursor Composer (Cmd+I)
# 2. Paste the full document below
# 3. Cursor will use this as context for all code generation

${sections
  .map(
    (s) => `## ${s.id}: ${s.name} [${s.phase}]

${s.content}
`
  )
  .join("\n---\n\n")}
`;
    },
  },
  bolt: {
    name: "Bolt",
    description: "Single-prompt format for Bolt.new",
    format: (sections, projectName) => {
      return `Build me a complete application called "${projectName}". Here is the full specification:

${sections
  .map((s) => `### ${s.name}\n${s.content}`)
  .join("\n\n")}

Build this as a complete, working application. Deploy it when done.`;
    },
  },
};

const ExportPanel = ({ sections, projectName }: ExportPanelProps) => {
  const { toast } = useToast();
  const [selectedPlatform, setSelectedPlatform] = useState<Platform>("lovable");
  const [copied, setCopied] = useState(false);

  const formatted = PLATFORM_INFO[selectedPlatform].format(sections, projectName);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(formatted);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({ title: `PRD copied for ${PLATFORM_INFO[selectedPlatform].name}!` });
  };

  const handleDownload = () => {
    const blob = new Blob([formatted], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${projectName.replace(/\s+/g, "-").toLowerCase()}-prd-${selectedPlatform}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "PRD downloaded!" });
  };

  return (
    <div className="space-y-4">
      <div>
        <h3 className="font-display text-lg font-bold">Export Your PRD</h3>
        <p className="text-sm text-muted-foreground font-body">
          Choose your target platform for optimized prompt formatting.
        </p>
      </div>

      {/* Platform selector */}
      <div className="grid grid-cols-3 gap-2">
        {(Object.keys(PLATFORM_INFO) as Platform[]).map((p) => (
          <button
            key={p}
            onClick={() => setSelectedPlatform(p)}
            className={`p-3 rounded-md border text-center transition-all ${
              selectedPlatform === p
                ? "border-primary bg-primary/10"
                : "border-border hover:border-primary/40"
            }`}
          >
            <p className="font-body text-sm font-medium">{PLATFORM_INFO[p].name}</p>
            <p className="text-[10px] text-muted-foreground font-body mt-0.5">
              {PLATFORM_INFO[p].description}
            </p>
          </button>
        ))}
      </div>

      {/* Preview */}
      <div className="glass-card p-4 max-h-48 overflow-y-auto">
        <pre className="text-xs font-body text-muted-foreground whitespace-pre-wrap">
          {formatted.slice(0, 500)}…
        </pre>
      </div>

      {/* Actions */}
      <div className="flex gap-2">
        <Button onClick={handleCopy} className="flex-1">
          {copied ? (
            <>
              <Check className="w-4 h-4 mr-1" /> Copied!
            </>
          ) : (
            <>
              <Copy className="w-4 h-4 mr-1" /> Copy for {PLATFORM_INFO[selectedPlatform].name}
            </>
          )}
        </Button>
        <Button variant="outline" onClick={handleDownload}>
          <Download className="w-4 h-4 mr-1" /> .md
        </Button>
      </div>
    </div>
  );
};

export default ExportPanel;
