import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Check, Download } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface PRDSection {
  id: string;
  name: string;
  phase: string;
  content: string;
}

interface ExportPanelProps {
  sections: PRDSection[];
  projectName: string;
}

type Platform = "lovable" | "cursor" | "bolt";

interface PromptStep {
  label: string;
  subtitle: string;
  content: string;
}

function buildSteps(sections: PRDSection[], projectName: string, platform: Platform): PromptStep[] {
  if (platform === "bolt") {
    return [
      {
        label: "Full Prompt",
        subtitle: "Paste into Bolt.new",
        content: `Build me a complete application called "${projectName}". Here is the full specification:\n\n${sections.map((s) => `### ${s.name}\n${s.content}`).join("\n\n")}\n\nBuild this as a complete, working application. Deploy it when done.`,
      },
    ];
  }

  if (platform === "cursor") {
    return [
      {
        label: "Full PRD",
        subtitle: "Paste into Cursor Composer (Cmd+I)",
        content: `# ${projectName} — PRD for Cursor\n# Generated by Prompt Pilot (VibeCoder Studio)\n\n${sections.map((s) => `## ${s.id}: ${s.name} [${s.phase}]\n\n${s.content}`).join("\n\n---\n\n")}`,
      },
    ];
  }

  // Lovable: 3 steps
  const plan = sections.filter((s) => s.phase === "Plan");
  const build = sections.filter((s) => s.phase === "Build");
  const improve = sections.filter((s) => s.phase === "Improve");

  const header = `# ${projectName} — Generated by Prompt Pilot (VibeCoder Studio)\n\n`;

  return [
    {
      label: "Step 1: Foundation",
      subtitle: "Vision, UX flows & database schema",
      content: `${header}## PROMPT 1 OF 3 — FOUNDATION\nPaste this into Lovable first. This sets up your project structure, user experience, and data model.\n\n${plan.map((s) => `### ${s.id}: ${s.name}\n${s.content}`).join("\n\n")}`,
    },
    {
      label: "Step 2: Build",
      subtitle: "Full app, SaaS logic & design system",
      content: `${header}## PROMPT 2 OF 3 — BUILD\nPaste this after Step 1 is done building. This adds full application features on top of the foundation.\n\n${build.map((s) => `### ${s.id}: ${s.name}\n${s.content}`).join("\n\n")}`,
    },
    {
      label: "Step 3: Polish",
      subtitle: "Advanced features, QA & optimization",
      content: `${header}## PROMPT 3 OF 3 — POLISH\nPaste this last. This adds advanced features, fixes edge cases, and optimizes performance.\n\n${improve.map((s) => `### ${s.id}: ${s.name}\n${s.content}`).join("\n\n")}`,
    },
  ];
}

const PLATFORM_INFO: Record<Platform, { name: string; description: string }> = {
  lovable: { name: "Lovable", description: "3-step guided paste workflow" },
  cursor: { name: "Cursor", description: "Single prompt for Composer" },
  bolt: { name: "Bolt", description: "Single prompt for Bolt.new" },
};

const ExportPanel = ({ sections, projectName }: ExportPanelProps) => {
  const { toast } = useToast();
  const [selectedPlatform, setSelectedPlatform] = useState<Platform>("lovable");
  const [copiedSteps, setCopiedSteps] = useState<Set<number>>(new Set());

  const steps = buildSteps(sections, projectName, selectedPlatform);

  const handleCopyStep = async (index: number) => {
    await navigator.clipboard.writeText(steps[index].content);
    setCopiedSteps((prev) => new Set(prev).add(index));
    toast({ title: `${steps[index].label} copied!` });
  };

  const handleDownload = () => {
    const full = steps.map((s) => s.content).join("\n\n" + "━".repeat(60) + "\n\n");
    const blob = new Blob([full], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${projectName.replace(/\s+/g, "-").toLowerCase()}-prd-${selectedPlatform}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Full PRD downloaded as .md!" });
  };

  // Reset checkmarks when platform changes
  const handlePlatformChange = (p: Platform) => {
    setSelectedPlatform(p);
    setCopiedSteps(new Set());
  };

  const allCopied = copiedSteps.size === steps.length;

  return (
    <div className="space-y-4">
      <div>
        <h3 className="font-display text-lg font-bold">Export Your PRD</h3>
        <p className="text-sm text-muted-foreground font-body">
          Choose your target platform, then copy each step in order.
        </p>
      </div>

      {/* Platform selector */}
      <div className="grid grid-cols-3 gap-2">
        {(Object.keys(PLATFORM_INFO) as Platform[]).map((p) => (
          <button
            key={p}
            onClick={() => handlePlatformChange(p)}
            className={`p-3 rounded-md border text-center transition-all ${
              selectedPlatform === p
                ? "border-primary bg-primary/10"
                : "border-border hover:border-primary/40"
            }`}
          >
            <p className="font-body text-sm font-medium">{PLATFORM_INFO[p].name}</p>
            <p className="text-[10px] text-muted-foreground font-body mt-0.5">
              {PLATFORM_INFO[p].description}
            </p>
          </button>
        ))}
      </div>

      {/* Per-step copy buttons */}
      <div className="space-y-2">
        {steps.map((step, i) => {
          const isCopied = copiedSteps.has(i);
          const isPrevDone = i === 0 || copiedSteps.has(i - 1);

          return (
            <div
              key={i}
              className={`flex items-center gap-3 p-3 rounded-md border transition-all ${
                isCopied
                  ? "border-green-500/50 bg-green-500/5"
                  : isPrevDone
                  ? "border-border"
                  : "border-border/50 opacity-50"
              }`}
            >
              {/* Step number / checkmark */}
              <div
                className={`flex-shrink-0 w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold ${
                  isCopied
                    ? "bg-green-500 text-white"
                    : "bg-muted text-muted-foreground"
                }`}
              >
                {isCopied ? <Check className="w-4 h-4" /> : i + 1}
              </div>

              {/* Label */}
              <div className="flex-1 min-w-0">
                <p className="font-body text-sm font-medium truncate">{step.label}</p>
                <p className="text-[10px] text-muted-foreground font-body">{step.subtitle}</p>
              </div>

              {/* Copy button */}
              <Button
                size="sm"
                variant={isCopied ? "outline" : "default"}
                onClick={() => handleCopyStep(i)}
                disabled={!isPrevDone}
                className="flex-shrink-0"
              >
                {isCopied ? (
                  <>
                    <Check className="w-3.5 h-3.5 mr-1" /> Copied
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5 mr-1" /> Copy
                  </>
                )}
              </Button>
            </div>
          );
        })}
      </div>

      {/* Completion message */}
      {allCopied && (
        <div className="p-3 rounded-md bg-green-500/10 border border-green-500/30 text-center">
          <p className="text-sm font-body font-medium text-green-400">
            ✅ All steps copied! Paste them into {PLATFORM_INFO[selectedPlatform].name} in order.
          </p>
        </div>
      )}

      {/* Download full .md */}
      <Button variant="outline" onClick={handleDownload} className="w-full">
        <Download className="w-4 h-4 mr-1" /> Download Full PRD (.md)
      </Button>
    </div>
  );
};

export default ExportPanel;
